name: server

services:
  air:
    build:
      context: ../..
      dockerfile: deploy/dev/air/Dockerfile
    ports:
      - "${PORT}:8080"
    volumes:
      - ../../:/app
      - ./tmp:/app/tmp 
    profiles:
      - dev

  server:
    build:
      context: ../..
      dockerfile: deploy/prod/docker/Dockerfile
    ports:
      - "${PORT}:8080"
    profiles:
      - prod 